//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationLibrary.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assest Info.
        /// </summary>
        public static string Assest_Info {
            get {
                return ResourceManager.GetString("Assest_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add assest to center.
        /// </summary>
        public static string AssestAdd {
            get {
                return ResourceManager.GetString("AssestAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Assest.
        /// </summary>
        public static string AssestEdit {
            get {
                return ResourceManager.GetString("AssestEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assests in Centers.
        /// </summary>
        public static string AssestsCenters {
            get {
                return ResourceManager.GetString("AssestsCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barcode.
        /// </summary>
        public static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center info.
        /// </summary>
        public static string center_info {
            get {
                return ResourceManager.GetString("center_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Center.
        /// </summary>
        public static string centerAdd {
            get {
                return ResourceManager.GetString("centerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Center.
        /// </summary>
        public static string centerEdit {
            get {
                return ResourceManager.GetString("centerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers/Stations.
        /// </summary>
        public static string centers {
            get {
                return ResourceManager.GetString("centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Type.
        /// </summary>
        public static string centerType {
            get {
                return ResourceManager.GetString("centerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a center.
        /// </summary>
        public static string Choose_center {
            get {
                return ResourceManager.GetString("Choose_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Center Type.
        /// </summary>
        public static string Choose_centerType {
            get {
                return ResourceManager.GetString("Choose_centerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose material.
        /// </summary>
        public static string Choose_Material {
            get {
                return ResourceManager.GetString("Choose_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose station.
        /// </summary>
        public static string Choose_Station {
            get {
                return ResourceManager.GetString("Choose_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Station.
        /// </summary>
        public static string Choose_Station_Please {
            get {
                return ResourceManager.GetString("Choose_Station_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Supervisor.
        /// </summary>
        public static string Choose_supervisor {
            get {
                return ResourceManager.GetString("Choose_supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string Confirm_New_Password {
            get {
                return ResourceManager.GetString("Confirm New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Care.
        /// </summary>
        public static string Customer_Care {
            get {
                return ResourceManager.GetString("Customer_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string Follow_Us {
            get {
                return ResourceManager.GetString("Follow_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Quantity.
        /// </summary>
        public static string fuel_qty {
            get {
                return ResourceManager.GetString("fuel_qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Top.
        /// </summary>
        public static string Go_to_Top {
            get {
                return ResourceManager.GetString("Go to Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobe Title.
        /// </summary>
        public static string JobeTitle {
            get {
                return ResourceManager.GetString("JobeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main management office.
        /// </summary>
        public static string mainOffice {
            get {
                return ResourceManager.GetString("mainOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Info.
        /// </summary>
        public static string Material_Info {
            get {
                return ResourceManager.GetString("Material_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Material.
        /// </summary>
        public static string MaterialAdd {
            get {
                return ResourceManager.GetString("MaterialAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Material.
        /// </summary>
        public static string MaterialEdit {
            get {
                return ResourceManager.GetString("MaterialEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy for Life.
        /// </summary>
        public static string motto {
            get {
                return ResourceManager.GetString("motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value for searching.
        /// </summary>
        public static string Msg_input_val_for_search {
            get {
                return ResourceManager.GetString("Msg_input_val_for_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thers is no data to view please add some.
        /// </summary>
        public static string Msg_Thers_is_no_data {
            get {
                return ResourceManager.GetString("Msg_Thers_is_no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data found.
        /// </summary>
        public static string no_data_found {
            get {
                return ResourceManager.GetString("no_data_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Location.
        /// </summary>
        public static string Our_Location {
            get {
                return ResourceManager.GetString("Our_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Pic {
            get {
                return ResourceManager.GetString("Pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sahm.
        /// </summary>
        public static string sahm {
            get {
                return ResourceManager.GetString("sahm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string signe_in {
            get {
                return ResourceManager.GetString("signe_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahm Gulf Fuel Company.
        /// </summary>
        public static string site_title {
            get {
                return ResourceManager.GetString("site_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string site_title_part1 {
            get {
                return ResourceManager.GetString("site_title_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulf Fuel Company.
        /// </summary>
        public static string site_title_part2 {
            get {
                return ResourceManager.GetString("site_title_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string supervisor {
            get {
                return ResourceManager.GetString("supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At our fuel stations, we provide more than just fuel - we offer a complete experience. Our station is equipped with state-of-the-art technology, including an automated pricing system and closed-circuit camera surveillance, ensuring your safety and convenience. We take environmental management seriously. Our staff is trained to respond to emergencies, and we have detailed emergency response procedures in place. Choose us for a fueling experience that goes beyond just filling up your tank..
        /// </summary>
        public static string text1 {
            get {
                return ResourceManager.GetString("text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sahem&quot; is a company specialized in providing fuel services for cars in the Kingdom of Saudi Arabia, as it is characterized by modern and advanced technologies to provide high-quality fuel to drivers. &quot;Sahem&quot; includes many fuel tanks distributed throughout the different regions in the Kingdom of Saudi Arabia, and is committed to providing the best possible services to its customers.
        ///
        ///Sahem applies the highest safety standards to ensure the protection of drivers and employees, and relies on effective environ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string text2 {
            get {
                return ResourceManager.GetString("text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem..
        /// </summary>
        public static string there_is_a_problem {
            get {
                return ResourceManager.GetString("there is a problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose us.
        /// </summary>
        public static string title1 {
            get {
                return ResourceManager.GetString("title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a better experience.
        /// </summary>
        public static string title2 {
            get {
                return ResourceManager.GetString("title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why &quot;Sahm&quot;.
        /// </summary>
        public static string title3 {
            get {
                return ResourceManager.GetString("title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &quot;Sahm&quot;.
        /// </summary>
        public static string title4 {
            get {
                return ResourceManager.GetString("title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sahem&quot; is a company specialized in providing fuel services for cars in the Kingdom of Saudi Arabia..
        /// </summary>
        public static string title5 {
            get {
                return ResourceManager.GetString("title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are not authoriazed.
        /// </summary>
        public static string you_are_not_authoriazed {
            get {
                return ResourceManager.GetString("you are not authoriazed", resourceCulture);
            }
        }
    }
}
